export const PAGE = {
  TIMESHEET: 'TIMESHEET',
  PEOPLE: 'PEOPLE',
  PROJECTS: 'PROJECTS',
};

export const ADD = {
  PERSON: 'PERSON',
  PROJECT: 'PROJECT',
  PERSON_TO_PROJECT: 'PERSON_TO_PROJECT',
  TASK_TO_PROJECT: 'TASK_TO_PROJECT',
  ACTIVITY_TO_PROJECT: 'ACTIVITY_TO_PROJECT',
  TASK_FOR_ONESELF: 'TASK_FOR_ONESELF',
};
