/*
 *
 * ProjectPage constants
 *
 */

export const DEFAULT_ACTION = 'app/ProjectPage/DEFAULT_ACTION';
export const UPDATE_SELECTED_PROJECT_CODE = 'app/ProjectPage/UPDATE_SELECTED_PROJECT_CODE';
export const LOADED_SELECTED_PROJECT = 'app/ProjectPage/LOADED_SELECTED_PROJECT';
export const LOAD_PROJECT_CODES = 'app/ProjectPage/LOAD_PROJECT_CODES';
export const LOADED_PROJECT_CODES = 'app/ProjectPage/LOADED_PROJECT_CODES';
export const SELECTED_TAB_CHANGED = 'app/ProjectPage/SELECTED_TAB_CHANGED';
export const OTHER_PROJECT_CLICKED = 'app/ProjectPage/OTHER_PROJECT_CLICKED';
export const CHANGED_ACTIVITIES_TEXT_FILTER = 'app/ProjectPage/CHANGED_ACTIVITIES_TEXT_FILTER';
export const EXPAND_TASK_LIST_ITEM = 'app/ProjectPage/EXPAND_TASK_LIST_ITEM';
export const COLLAPSE_TASK_LIST_ITEM = 'app/ProjectPage/COLLAPSE_TASK_LIST_ITEM';
export const NEW_TASK_FORM_ID = 'app/ProjectPage/NEW_TASK_FORM_ID';
export const LAUNCH_NEW_TASK_DIALOG = 'app/ProjectPage/LAUNCH_NEW_TASK_DIALOG';
export const DISMISS_NEW_TASK_DIALOG = 'app/ProjectPage/DISMISS_NEW_TASK_DIALOG';
export const SUBMIT_NEW_TASK_FORM = 'app/ProjectPage/SUBMIT_NEW_TASK_FORM';
export const SUBMIT_NEW_TASK_FORM_AND_CLOSE_IT = 'app/ProjectPage/SUBMIT_NEW_TASK_FORM_AND_CLOSE_IT';
export const ENDED_SUBMIT_NEW_TASK = 'app/ProjectPage/ENDED_SUBMIT_NEW_TASK';
export const LAUNCH_NEW_ACTIVITY_DIALOG = 'app/ProjectPage/LAUNCH_NEW_ACTIVITY_DIALOG';
export const DISMISS_NEW_ACTIVITY_DIALOG = 'app/ProjectPage/DISMISS_NEW_ACTIVITY_DIALOG';
export const SUBMIT_NEW_ACTIVITY_FORM = 'app/ProjectPage/SUBMIT_NEW_ACTIVITY_FORM';
export const SUBMIT_NEW_ACTIVITY_FORM_AND_CLOSE_IT = 'app/ProjectPage/SUBMIT_NEW_ACTIVITY_FORM_AND_CLOSE_IT';
export const ENDED_SUBMIT_NEW_ACTIVITY = 'app/ProjectPage/ENDED_SUBMIT_NEW_ACTIVITY';
